-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 22:06:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema coracoralina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coracoralina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coracoralina` DEFAULT CHARACTER SET latin1 ;
USE `coracoralina` ;

-- -----------------------------------------------------
-- Table `coracoralina`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coracoralina`.`status` (
  `idstatus` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK: chave primaria da tabela \'status\'.',
  `descricao_status` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL COMMENT 'campo descricao:  descricao do status do livro na tabela \'status\'.',
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coracoralina`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coracoralina`.`emprestimo` (
  `idemprestimo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK: chave primaria da tabela \'emprestimo\'.',
  `data` DATETIME NOT NULL COMMENT 'campo data: cadastro da data do emprestimo na tabela \'emprestimo\'.',
  `acervo_idacervo` INT(11) NOT NULL COMMENT 'FK: chave estrangeira com relacionamento com a tabela \'acervo\'.',
  `funcionario_idfuncionario` INT(11) NOT NULL COMMENT 'FK: chave estrangeira com relacionamento com a tabela \'funcionario\'.',
  `status_idstatus` INT(11) NOT NULL COMMENT 'FK: chave estrangeira com relacionamento com a tabela \'status\'.',
  `usuario_idUsuario` INT(10) NOT NULL,
  PRIMARY KEY (`idemprestimo`),
  INDEX `fk_emprestimo_acervo1_idx` (`acervo_idacervo` ASC),
  INDEX `fk_emprestimo_status1_idx` (`status_idstatus` ASC),
  INDEX `fk_emprestimo_usuario1_idx` (`usuario_idUsuario` ASC),
  CONSTRAINT `fk_emprestimo_acervo1`
    FOREIGN KEY (`acervo_idacervo`)
    REFERENCES `coracoralina`.`acervo` (`idacervo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_emprestimo_status1`
    FOREIGN KEY (`status_idstatus`)
    REFERENCES `coracoralina`.`status` (`idstatus`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_emprestimo_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `coracoralina`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coracoralina`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coracoralina`.`perfil` (
  `idPerfil` INT(10) NOT NULL AUTO_INCREMENT COMMENT 'PK: chave primaria da tabela \'perfil\'.',
  `desricao_perfil` VARCHAR(100) NOT NULL COMMENT 'campo descricao: descricao do perfil na tabela \'perfil\'.',
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coracoralina`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coracoralina`.`usuario` (
  `idUsuario` INT(10) NOT NULL AUTO_INCREMENT COMMENT 'PK:chave primaria na tabela \'usuario\'.',
  `email` VARCHAR(50) NOT NULL COMMENT 'campo email: cadastro do email na tabela \'usuario\'.',
  `senha` VARCHAR(32) NOT NULL COMMENT 'campo senha: cadastro da senha na tabela \'usuario\'.',
  `nome` VARCHAR(60) NOT NULL,
  `dt_nasc` DATE NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `rg` VARCHAR(14) NOT NULL,
  `endereco` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `perfil_idPerfil` INT(10) NOT NULL COMMENT 'FK: chave estrangeira com relacionamento com a tabela \'perfil\'.',
  `emprestimo_idemprestimo` INT(11) NULL DEFAULT NULL COMMENT 'FK: chave estrangeira com relacionamento com a tabela \'emprestimo\'.',
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_perfil_idx` (`perfil_idPerfil` ASC),
  INDEX `fk_usuario_emprestimo1_idx` (`emprestimo_idemprestimo` ASC),
  CONSTRAINT `fk_usuario_emprestimo1`
    FOREIGN KEY (`emprestimo_idemprestimo`)
    REFERENCES `coracoralina`.`emprestimo` (`idemprestimo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`perfil_idPerfil`)
    REFERENCES `coracoralina`.`perfil` (`idPerfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coracoralina`.`acervo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coracoralina`.`acervo` (
  `idacervo` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK: chave primaria na tabela \'acervo\'.',
  `autor` VARCHAR(45) NOT NULL COMMENT 'campo autor: cadastro do autor do livro na tabela \'acervo\'.',
  `genero` VARCHAR(45) NOT NULL COMMENT 'campo genero: cadastro do genero literario na tabela \'acervo\'.',
  `data` DATETIME NOT NULL COMMENT 'campo data: cadastro da data do livrona tabela \'acervo\'.',
  `livro` VARCHAR(100) NOT NULL COMMENT 'campo livro: cadastro do livro na tabela \'acervo\'.',
  `sinopse` VARCHAR(500) NOT NULL COMMENT 'campo sinopse: cadastro da sinopse do livro na tabela \'acervo\'.',
  `usuario_idUsuario` INT(10) NOT NULL,
  PRIMARY KEY (`idacervo`),
  INDEX `fk_acervo_usuario1_idx` (`usuario_idUsuario` ASC),
  CONSTRAINT `fk_acervo_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `coracoralina`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coracoralina`.`doacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coracoralina`.`doacao` (
  `iddoacao` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK:chave primaria na tabela \'doacao\'.',
  `data` DATETIME NOT NULL COMMENT 'campo data: cadastro da data da doacao na tabela \'doacao\'.',
  `descricao_doacao` VARCHAR(100) NOT NULL COMMENT 'campo descricao: descricao da doacao do livro na tabela \'doacao\'.',
  `acervo_idacervo` INT(11) NOT NULL COMMENT 'FK: chave estrangeira com relacionamento com a tabela \'acervo\'.',
  PRIMARY KEY (`iddoacao`),
  INDEX `fk_doacao_acervo1_idx` (`acervo_idacervo` ASC),
  CONSTRAINT `fk_doacao_acervo1`
    FOREIGN KEY (`acervo_idacervo`)
    REFERENCES `coracoralina`.`acervo` (`idacervo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coracoralina`.`acervo_has_doacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coracoralina`.`acervo_has_doacao` (
  `acervo_idacervo` INT(11) NOT NULL COMMENT 'FK: acervo_idacervo chave estrangeira da tabela \'acervo\'.',
  `doacao_iddoacao` INT(11) NOT NULL COMMENT 'FK: doacao_iddoacao chave estrangeira da tabela \'doacao\'.',
  PRIMARY KEY (`acervo_idacervo`, `doacao_iddoacao`),
  INDEX `fk_acervo_has_doacao_doacao1_idx` (`doacao_iddoacao` ASC),
  INDEX `fk_acervo_has_doacao_acervo1_idx` (`acervo_idacervo` ASC),
  CONSTRAINT `fk_acervo_has_doacao_acervo1`
    FOREIGN KEY (`acervo_idacervo`)
    REFERENCES `coracoralina`.`acervo` (`idacervo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_acervo_has_doacao_doacao1`
    FOREIGN KEY (`doacao_iddoacao`)
    REFERENCES `coracoralina`.`doacao` (`iddoacao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coracoralina`.`devolucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coracoralina`.`devolucao` (
  `iddevolucao` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK:chave primaria da tabela \'devolucao\'.',
  `data` DATETIME NOT NULL COMMENT 'campo data: cadastro da data da devolucao do livro na tabela \'devolucao\'.',
  `emprestimo_idemprestimo1` INT(11) NOT NULL COMMENT 'FK: chave estrangeira com relacionamento com a tabela \'emprestimo\'.',
  `status_idstatus` INT(11) NOT NULL COMMENT 'FK: chave estrangeira com relacionamento com a tabela \'status\'.',
  PRIMARY KEY (`iddevolucao`),
  INDEX `fk_devolucao_emprestimo1_idx` (`emprestimo_idemprestimo1` ASC),
  INDEX `fk_devolucao_status1_idx` (`status_idstatus` ASC),
  CONSTRAINT `fk_devolucao_emprestimo1`
    FOREIGN KEY (`emprestimo_idemprestimo1`)
    REFERENCES `coracoralina`.`emprestimo` (`idemprestimo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_devolucao_status1`
    FOREIGN KEY (`status_idstatus`)
    REFERENCES `coracoralina`.`status` (`idstatus`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coracoralina`.`opiniao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coracoralina`.`opiniao` (
  `idopiniao` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK:chave primaria da tabela \'opiniao\'.',
  `descricao_opiniao` VARCHAR(1000) NOT NULL COMMENT 'campo descricao: descricao da opiao do leitor na tabela \'opiniao\'.',
  `leitor_idleitor` INT(10) NOT NULL COMMENT 'FK:chave estrangeira com relacionamento com a tabela \'leitor\'.',
  `acervo_idacervo` INT(11) NOT NULL COMMENT 'FK: chave estrangeira com relacionamento com a tabela \'acervo\'.',
  `nota` FLOAT(1,1) NOT NULL COMMENT 'campo nota: nota do leitor sobre o livro na tabela \'opiniao\'.',
  `usuario_idUsuario` INT(10) NOT NULL,
  PRIMARY KEY (`idopiniao`),
  INDEX `fk_opiniao_acervo1_idx` (`acervo_idacervo` ASC),
  INDEX `fk_opiniao_usuario1_idx` (`usuario_idUsuario` ASC),
  CONSTRAINT `fk_opiniao_acervo1`
    FOREIGN KEY (`acervo_idacervo`)
    REFERENCES `coracoralina`.`acervo` (`idacervo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opiniao_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `coracoralina`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coracoralina`.`usuario_has_acervo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coracoralina`.`usuario_has_acervo` (
  `usuario_idUsuario` INT(10) NOT NULL,
  `acervo_idacervo` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_idUsuario`, `acervo_idacervo`),
  INDEX `fk_usuario_has_acervo_acervo1_idx` (`acervo_idacervo` ASC),
  INDEX `fk_usuario_has_acervo_usuario1_idx` (`usuario_idUsuario` ASC),
  CONSTRAINT `fk_usuario_has_acervo_acervo1`
    FOREIGN KEY (`acervo_idacervo`)
    REFERENCES `coracoralina`.`acervo` (`idacervo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_acervo_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `coracoralina`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
